#!/usr/bin/python3
#正しく動作せず
user_input = input("数字を入力: ")

original_total = int(user_input)
total = original_total

while True:
    new_total = 0
    for number_char in str(total):
        number = int(number_char)
        new_total += number

    print("計算結果", total)

    if new_total < 10:
        break

    if new_total >= 10 and new_total % 11 == 0:
        print("11の倍数")
        break
