#!/bin/python3
# SPDX-FileCopyrightText: 2022 Ryuichi Ueda
# SPDX-License-Identifier: BSD-3-Clause

import sys

if len(sys.argv) > 1:
    user_input = ' '.join(sys.argv[1:])
    print("入力された文字:",user_input)
else:
    print("引数がない")
